# .github/workflows/ci.yml
# This file defines the GitHub Actions workflow for Continuous Integration.

name: Calculator Project CI/CD

# Controls when the workflow will run.
on:
  # Triggers the workflow on push events for the main branch.
  push:
    branches: [ "main" ]
  # Triggers the workflow on pull request events targeting the main branch.
  pull_request:
    branches: [ "main" ]

jobs:
  # A single job called "build-and-test".
  build-and-test:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    # A strategy matrix to run the job on multiple Python versions.
    strategy:
      matrix:
        python-version: ["3.8", "3.10", "3.12"]

    steps:
      # 1. Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up the specified Python version.
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # 3. Install build tools and test dependencies.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Build the package using the Makefile.
      #    This step compiles the C extension.
      - name: Build and Install Package
        run: make build

      # 5. Run all tests using the Makefile.
      #    This executes both 'make test_c' and 'make test_python'.
      - name: Run All Tests
        run: make test
